<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>
    <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
    <!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->
    <OutputType>Exe</OutputType>
    <RootNamespace>BlazorDemo.MAUI</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCssItems>false</EnableDefaultCssItems>
    <!-- Display name -->
    <ApplicationTitle>Blazor MAUI</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.blazormaui</ApplicationId>
    <ApplicationIdGuid>3C1B2C61-7A59-4FCC-AF5C-7FBCF36A03B6</ApplicationIdGuid>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
    <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
    <ValidateExecutableReferencesMatchSelfContained>false</ValidateExecutableReferencesMatchSelfContained>
    <MauiVersion>9.0.10</MauiVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />
    <!-- Images -->
    <MauiImage Include="Resources\Images\*" />
    <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />
    <!-- Custom Fonts -->
    <MauiFont Include="Resources\Fonts\*" />
    <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
    <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <MauiImage Include="Resources\Images\avatars\alex.jpg" />
    <MauiImage Include="Resources\Images\avatars\andrey.jpg" />
    <MauiImage Include="Resources\Images\avatars\anthony.jpg" />
    <MauiImage Include="Resources\Images\avatars\bogdan.jpg" />
    <MauiImage Include="Resources\Images\avatars\boris.jpg" />
    <MauiImage Include="Resources\Images\avatars\dennis.jpg" />
    <MauiImage Include="Resources\Images\avatars\dmitry.jpg" />
    <MauiImage Include="Resources\Images\avatars\elena.jpg" />
    <MauiImage Include="Resources\Images\avatars\kseniya.jpg" />
    <MauiImage Include="Resources\Images\avatars\lana.png" />
    <MauiImage Include="Resources\Images\avatars\margarita.jpg" />
    <MauiImage Include="Resources\Images\avatars\poline.png" />
    <MauiImage Include="Resources\Images\avatars\vlada.jpg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="DevExpress.Blazor" Version="24.2.*" />
    <PackageReference Include="DevExpress.Data" Version="24.2.*" />
    <PackageReference Include="DevExpress.Maui.Charts" Version="24.2.*" />
    <PackageReference Include="DevExpress.Maui.CollectionView" Version="24.2.*" />
    <PackageReference Include="DevExpress.Maui.Controls" Version="24.2.*" />
    <PackageReference Include="DevExpress.Maui.Editors" Version="24.2.*" />
  </ItemGroup>
  <ItemGroup> 
    <ProjectReference Include="..\BlazorDemo.Shared\BlazorDemo.Shared.csproj" />
  </ItemGroup>
</Project>
